polls/urls.py
from django.urls import path
from . import views
import re

app_name = 'polls'

urlpatterns = [
    path('', views.show_polls, name='show_polls'),
    path('<int:pk>', views.detail_poll, name = 'detail_poll'),
    path('<int:pk>/vote', views.vote, name = 'vote'),
    path('<int:pk>/results', views.results, name='results')
    ]

portfolio/urls.py
from django.urls import path
from . import views
import re

app_name = 'main'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
]

portfolio_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('polls/', include('polls.urls')),
    path('feedback/', include('write.urls'))
]

write/urls.py
from django.urls import path
from . import views
import re

app_name = 'feedback'

urlpatterns = [
    path('', views.feedback, name = 'feedback')
]

polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

portfolio/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def get_short_text(self):
        try:
            short_text = (self.text[:100]+'...')
        except:
            short_text = self.text
        return short_text

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

write/models.py
from django.db import models

# Create your models here.
class Comment(models.Model):
    name = models.CharField(max_length=200)
    email = models.CharField(max_length=100)
    text = models.TextField()

polls/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from .models import Question, Choice
from django.urls import reverse
from django.http import HttpResponseRedirect
# Create your views here.
def show_polls(request):
    polls = get_list_or_404(Question)
    content = {'polls':polls}
    return render(request, "polls/index.html", content)
def detail_poll(request, pk):
    poll = get_object_or_404(Question, pk=pk)
    content = {'poll':poll}
    return render(request, "polls/detail.html", content)
def vote(request, pk):
    question = get_object_or_404(Question,pk=pk)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
        print(selected_choice)
    except (KeyError, Choice.DoesNotExist):
        content = {'question':question, 'error_message':'You didn\'t select a choice'}
        return render(request, 'polls/detail.html', content)
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(pk,)))

    #return render(request, "polls/vote.html", content)
def results(request,pk):
    content = {}
    return render(request, "polls/results.html", content)

portfolio/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.utils import timezone
from .models import Post
import random
# Create your views here.
def post_list(request):
    POSTS_ON_PAGES = 3
    #posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')[:5]
    all_posts = get_list_or_404(Post, published_date__lte=timezone.now())
    num_pages = int(len(all_posts)/POSTS_ON_PAGES)+1 #количество страниц
    pages = range(1, num_pages+1)
    posts = all_posts[:POSTS_ON_PAGES]
    random_post = random.choice(posts)
    content = {'posts':posts, 'random_post':random_post, 'pages':pages}
    return render(request, 'portfolio/index.html', content)
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'portfolio/post_detail.html', {'post': post})

write/views.py
from django.shortcuts import render

# Create your views here.

def feedback(request):
    content = {}
    return render(request, 'write/feedback.html', content)

polls/templates/polls/detail.html
{% extends "portfolio/base.html" %}
{% block content %}
    <div class="col-sm-8 col-md-7 py-4">
    <form action="{% url 'polls:vote' poll.id %}" method="post">
    {% csrf_token %}
        <h4>{{ poll.question_text }}</h4>
        <p>{{ poll.pub_date }}</p>
        {% for choice in poll.choice_set.all %}
            <input type = "radio" name = "choice" id = "choice{{ forloop.counter }}" value = {{ choice.id }}>
            <label for ="choice">{{ forloop.counter }}. {{ choice.choice_text }} </label><br>
        {% endfor %}
    <input type="submit" value="vote">
    </form>
    </div>
{% endblock %}

polls/templates/polls/index.html
{% extends 'portfolio/base.html' %}
{% block content %}
{% for poll in polls %}
    <div class="col-sm-8 col-md-7 py-4">
        <h4><a href = "{% url 'polls:detail_poll' poll.id %}">{{ poll.question_text }}</a></h4>
        <p class = "text-muted">{{ poll.pub_date }}</p>

    </div>
{% endfor %}
{% endblock %}

polls/templates/polls/results.html
{% extends 'portfolio/base.html' %}
results

polls/templates/polls/vote.html
{% extends 'portfolio/base.html' %}
vote

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Demin Dmitriy">
    <title>Portfol.io</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/album/">

    <!-- Bootstrap core CSS -->
<link href="{% static 'assets/dist/css/bootstrap.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/portfolio.css' %}">
  </head>
  <body>
    <header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">This website was created using Django, MySQL and Bootstrap</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="https://github.com/woozlic" class="text-white">GitHub: woozlic</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="{% url 'main:post_list' %}" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Dema's portfolio</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main role="main">

  {% block top %}

  {% endblock %}

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">
        {% block content %}
        {% endblock %}
       </div>
    </div>
  </div>

</main>

<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>Dema's portfolio</p>
    <p>My GitHub: <a href="https://github.com/woozlic">woozlic</a>.</p>
  </div>
</footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="{% static "/assets/js/vendor/jquery.slim.min.js" %} ><\/script>')</script><script src="{% static '/assets/dist/js/bootstrap.bundle.js' %} "></script></body>
</html>

portfolio/templates/portfolio/index.html
{% extends 'portfolio/base.html' %}
{% block top %}
<section class="jumbotron text-center">
    <div class="container">
      <h1>Dema's portfolio</h1>
      <p class="lead text-muted">This website was created using Django, MySQL and Bootstrap</p>
      <p>
        <a href="#" class="btn btn-primary my-2">Write me to hire</a>
        <a href="{% url 'main:post_detail'  random_post.pk %}" class="btn btn-secondary my-2">Look at random project</a>
      </p>
    </div>
  </section>
{% endblock %}

{% block content %}
{% for post in posts %}
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
            <div class="card-body">
                <h3><a href = '{% url "main:post_detail" post.pk %} '>{{ post.title }}</a></h3>
              <p class="card-text">{{ post.get_short_text }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">{{post.published_date}}</small>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    <div class = 'container'>
<ul class="list-unstyled">
<li>
    {% for page in pages %}

        <a href ="#">{{ page }}</a>

    {% endfor %}
</li>
</ul>
    </div>
{% endblock %}

portfolio/templates/portfolio/post_detail.html
{% extends 'portfolio/base.html' %}
{% block content %}
    <div class = "container">
<h1>{{ post.title }}</h1>
<p class="lead text-muted">{{ post.text }}</p>
    </div>
{% endblock %}

portfolio/templates/portfolio/post_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/portfolio.css' %}">
    <meta charset="UTF-8">
    <title>aaaaa)</title>
</head>
<body>
{% for post in posts %}
    <h1>{{ post.title }}</h1>
    <h4>Author: {{ post.author }}</h4>
    <p><b>{{ post.text|linebreaksbr }}</b></p>
    <p>published date: {{ post.published_date }}</p>
{% endfor %}


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

write/templates/write/feedback.html
{{ extends 'portfolio/base.html' }}

{% block content %}
jopaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
{% endblock %}